### ISSUE TITLE
Channels

### ISSUE THREAD

**Issue by DUFCLiam** [PluginService/YouFreedom#20]
Adding channels.

**Comment by AvalancheYT** [comment]
Can you be more descriptive.

**Comment by DUFCLiam** [comment]
@AvalancheYT By that I mean like all the videos a person uploaded would be linked on the same page like YouTube channels.

**Comment by DUFCLiam** [comment]
Added since https://github.com/PluginService/YouFreedom/commit/a64a6173071cc648ff3e46dca4fb334f7cd8ad0f
